# Generated by Django 2.2.7 on 2019-11-14 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Owner_Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='application/img')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.City')),
                ('owner', models.ForeignKey(on_delete=models.SET('null'), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('code', models.IntegerField()),
                ('total', models.IntegerField()),
                ('owner_ship', models.ForeignKey(on_delete=models.SET('null'), to='rent.Owner_Ship')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Rent_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('owner_ship', models.ForeignKey(on_delete=models.SET('null'), to='rent.Owner_Ship')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.Reservation')),
            ],
            options={
                'verbose_name_plural': 'Fechas de Alquileres',
            },
        ),
    ]
