# Generated by Django 2.2.7 on 2019-11-15 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rent_Date',
            new_name='Date_Rent',
        ),
        migrations.AddField(
            model_name='reservation',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('null'), to=settings.AUTH_USER_MODEL),
        ),
    ]
