# Generated by Django 2.2.7 on 2019-11-15 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0002_auto_20191115_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='rent/img')),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='RentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('property', models.ForeignKey(default=1, on_delete=models.SET('null'), to='rent.Property')),
            ],
            options={
                'verbose_name_plural': 'Fechas de Alquileres',
            },
        ),
        migrations.RemoveField(
            model_name='owner_ship',
            name='city',
        ),
        migrations.RemoveField(
            model_name='owner_ship',
            name='owner',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='code',
            new_name='reservationCode',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='renter',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='owner_ship',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='Date_Rent',
        ),
        migrations.DeleteModel(
            name='Owner_Ship',
        ),
        migrations.AddField(
            model_name='rentdate',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.Reservation'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.City'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET('null'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='property',
            field=models.ForeignKey(default=1, on_delete=models.SET('null'), to='rent.Property'),
        ),
    ]
