# Generated by Django 2.2.7 on 2019-11-15 05:00

from django.db import migrations, models
import rent.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20191115_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdate',
            name='property',
            field=models.ForeignKey(default=rent.models.Property, on_delete=models.SET('null'), to='rent.Property'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='property',
            field=models.ForeignKey(default=rent.models.Property, on_delete=models.SET('null'), to='rent.Property'),
        ),
    ]
