# Generated by Django 2.2.7 on 2019-11-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_auto_20191115_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(null=True, upload_to='static/rent/img/'),
        ),
    ]
